# Generated by Django 3.1.5 on 2021-01-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=10, null=True)),
                ('image', models.ImageField(upload_to='media/')),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('phone', models.PositiveIntegerField()),
                ('room_no', models.CharField(max_length=5)),
                ('subject', models.TextField()),
            ],
            options={
                'db_table': 'teacher',
                'managed': True,
            },
        ),
    ]
