# Generated by Django 3.1.5 on 2021-01-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_db', '0003_auto_20210127_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.PositiveBigIntegerField(),
        ),
    ]
